const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';

const ADD_NEW_PAGE = 'ADD_NEW_PAGE';

export { ADD_NEW_PAGE, FETCH_ITEM_REQUEST, FETCH_ITEM_SUCCESS, FETCH_ITEM_FAILURE };